name: ritmo_mortal_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  proximity_sensor: ^1.3.8
  just_audio: ^0.9.36
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/imagenes/barquitoIA.jpg
    - lib/assets/imagenes/logo.png
    - lib/assets/imagenes/barcoia.jpg
    - lib/assets/imagenes/fondojuego.png
    - lib/assets/imagenes/fondojuego.png

    - lib/assets/imagenes/alarma.png
    - lib/assets/imagenes/calaveraroja.png
    - lib/assets/imagenes/coparoja.png
    - lib/assets/imagenes/carro.png
    - lib/assets/imagenes/pelota.png

    - lib/assets/imagenes/cofre.png
    - lib/assets/imagenes/pirata.png
    - lib/assets/imagenes/copapirata.png
    - lib/assets/imagenes/gorropirata.png
    - lib/assets/imagenes/mapa.png

    - assets/sonidos/error.mp3
    - assets/sonidos/grito.mp3
    - assets/sonidos/moneda.mp3

  fonts:
    - family: JollyLodger
      fonts:
        - asset: fonts/JollyLodger-Regular.ttf
